# Naive Bayes

In [1]:
import pandas as pd

## Importing the Dataset

In [2]:
dataset = pd.read_csv("/workspaces/Supervised-Machine-Learning/Datasets/adult.csv")
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   39              32560 non-null  int64
 1    State-gov      32560 non-null  object
 2    77516          32560 non-null  int64
 3    Bachelors      32560 non-null  object
 4    13             32560 non-null  int64
 5    Never-married  32560 non-null  object
 6    Adm-clerical   32560 non-null  object
 7    Not-in-family  32560 non-null  object
 8    White          32560 non-null  object
 9    Male           32560 non-null  object
 10   2174           32560 non-null  int64
 11   0              32560 non-null  int64
 12   40             32560 non-null  int64
 13   United-States  32560 non-null  object
 14   <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [3]:
display(dataset)

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Applying Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X = dataset.iloc[:, :-1].copy()
y = dataset.iloc[:, -1].copy()

categorical_features = [1, 3, 5, 6, 7, 8, 9, 13]
for feature in categorical_features:
    X.iloc[:, feature] = le.fit_transform(X.iloc[:, feature])

y_encoded = le.fit_transform(y)
X_encoded = X.to_numpy(dtype=float)

In [6]:
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()

numerical_features = [0, 2, 4, 10, 11, 12]
X_gaussian = X_encoded.copy()

for feature in numerical_features:
    X_gaussian[:, feature] = sc.fit_transform(X_gaussian[:, feature].reshape(-1, 1)).reshape(-1)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_gaussian, y_encoded, test_size=0.25, random_state=324
)

## Gaussian Naive Bayes

In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[5895  298]
 [1310  637]]
0.8024570024570025

## Multinomial Naive Bayes

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.25, random_state=324
)

In [11]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[6192    1]
 [1908   39]]
0.7654791154791155

## Complement Naive Bayes

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.25, random_state=324
)

In [15]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train, y_train)

ComplementNB()

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[3920 2273]
 [ 313 1634]]
0.6823095823095823

## Bernoulli Naive Bayes

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.25, random_state=324
)

In [19]:
from sklearn.preprocessing import MinMaxScaler, Binarizer
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

binarizer = Binarizer(threshold=0.5)
X_train = binarizer.fit_transform(X_train)
X_test = binarizer.transform(X_test)

In [20]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classifier.score(X_test, y_test))

[[4532 1661]
 [ 551 1396]]
0.7282555282555283
0.7282555282555283

## Categorical Naive Bayes

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.25, random_state=324
)

In [23]:
from sklearn.preprocessing import KBinsDiscretizer
kbd = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
X_train = kbd.fit_transform(X_train)
X_test = kbd.transform(X_test)

/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 7 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 8 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 9 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 10 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 11 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 12 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 13 are removed. Consider decreasing the number of bins.
  warnings.warn(

In [24]:
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train, y_train)

CategoricalNB()

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classifier.score(X_test, y_test))

[[5057 1136]
 [ 513 1434]]
0.7974201474201474
0.7974201474201474

## Naive Bayes Score Output

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, MinMaxScaler, Binarizer, KBinsDiscretizer
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.25, random_state=324
)

scores = {}

# Gaussian Naive Bayes
rb = RobustScaler()
X_train_rb = X_train.copy()
X_test_rb = X_test.copy()
numerical_features = [0, 2, 4, 10, 11, 12]
for feature in numerical_features:
    X_train_rb[:, feature] = rb.fit_transform(X_train_rb[:, feature].reshape(-1, 1)).reshape(-1)
    X_test_rb[:, feature] = rb.transform(X_test_rb[:, feature].reshape(-1, 1)).reshape(-1)
model = GaussianNB()
model.fit(X_train_rb, y_train)
scores['GaussianNB'] = model.score(X_test_rb, y_test)

# Multinomial Naive Bayes
mm = MinMaxScaler()
X_train_mm = mm.fit_transform(X_train)
X_test_mm = mm.transform(X_test)
model = MultinomialNB()
model.fit(X_train_mm, y_train)
scores['MultinomialNB'] = model.score(X_test_mm, y_test)

# Complement Naive Bayes
model = ComplementNB()
model.fit(X_train_mm, y_train)
scores['ComplementNB'] = model.score(X_test_mm, y_test)

# Bernoulli Naive Bayes
binz = Binarizer(threshold=0.5)
X_train_bin = binz.fit_transform(X_train_mm)
X_test_bin = binz.transform(X_test_mm)
model = BernoulliNB()
model.fit(X_train_bin, y_train)
scores['BernoulliNB'] = model.score(X_test_bin, y_test)

# Categorical Naive Bayes
kbd = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
X_train_cat = kbd.fit_transform(X_train)
X_test_cat = kbd.transform(X_test)
model = CategoricalNB()
model.fit(X_train_cat, y_train)
scores['CategoricalNB'] = model.score(X_test_cat, y_test)

pd.DataFrame(list(scores.items()), columns=['Model', 'Score']).sort_values(by='Score', ascending=False).reset_index(drop=True)

/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 1 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 4 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 7 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 8 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 9 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 10 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 11 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 12 are removed. Consider decreasing the number of bins.
  warnings.warn(
/workspaces/Supervised-Machine-Learning/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 13 are removed. Consider decreasing the number of bins.
  warnings.warn(

           Model     Score
0     GaussianNB  0.802457
1  CategoricalNB  0.797420
2  MultinomialNB  0.765479
3    BernoulliNB  0.728256
4   ComplementNB  0.682310